- name: Check if rust/cargo is installed
  command: which cargo
  register: cargo_installed
  ignore_errors: true
  changed_when: false
  failed_when: false

- name: Install rust/cargo
  when: cargo_installed.rc != 0
  become: false
  block:
    - name: Download rustup-init script
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup-init.sh
        mode: "0755"
    - name: Execute rustup-init script
      command: /tmp/rustup-init.sh -y
      args:
        creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"
    - name: Init env
      command: source "{{ ansible_env.HOME }}/.cargo/env"
      args:
        executable: /bin/bash
      changed_when: false

- name: Run rustup if already installed
  when: cargo_installed.rc == 0
  become: false
  ansible.builtin.command: rustup update
  args:
    warn: false
  register: rustup_result
  changed_when: "'unchanged' not in rustup_result.stdout"

- name: Install zellij
  community.general.cargo:
    name: zellij

- name: Install Yazi
  community.general.cargo:
    name:
      - yazi-fm
      - yazi-cli
