---
- hosts: localhost
  connection: local
  become: no
  tasks:

    - name: Check if .local/bin is in PATH
      command: "grep '.local/bin' /home/{{ ansible_user_id }}/.bashrc"
      register: checkbashrc
      check_mode: no
      ignore_errors: yes
      changed_when: no

    - name: Add to path if not present
      lineinfile:
        path: "/home/{{ ansible_user_id }}/.bashrc"
        line: "export PATH=$PATH:/home/{{ ansible_user_id }}/.local/bin"
      when: checkbashrc.rc == 1

    - name: .local/bin/ to Path in .zshrc
      lineinfile:
        path: "/home/{{ ansible_user_id }}/.zshrc"
        line: "export PATH=$PATH:/home/{{ ansible_user_id }}/.local/bin"
        insertbefore: "BOF"

    - name: "Install system packages"
      become: yes
      apt:
        name:
        - aptitude
        - tree
        - locate
        - fd-find
        - neofetch
        - tmux
        - zsh
        - apt-transport-https
        state: latest
        update_cache: true
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Prepare VSCode dependencies
      become: yes
      apt:
        name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        state: latest

    - name: Add microsoft apt key
      become: yes
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
    - name: Add VS Code apt repostitory
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        state: present
        filename: vscode
    - name: Install VS Code
      become: yes
      apt:
        name: code
        state: present

    - name: Include zsh role
      include_role:
        name: zsh
      when: install_zsh|default(true)

    - name: "Configure vi-keybindings for tmux"
      lineinfile:
        dest: "/home/{{ ansible_user_id }}/.tmux.conf"
        line: "set-window-option -g mode-keys vi"
        create: true

    - name: "Symlink fdfind to fd"
      become: yes
      file:
        src: /usr/bin/fdfind
        path: /usr/bin/fd
        state: link

    # For installing logseq and other AppImage applications
    - name: Install AppImageLauncher via PPA
      become: yes
      apt_repository:
        repo: "ppa:appimagelauncher-team/stable"
        state: present
      notify: Update apt cache

    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes

    - name: Install AppImageLauncher
      become: yes
      apt:
        name: appimagelauncher
        state: present

    - name: Include fzf role
      include_role:
        name: fzf
      when: install_fzf|default(true)

    - name: Include zoxide role
      include_role:
        name: zoxide
      when: install_zoxide|default(true)

    - name: Include neovim role
      include_role:
        name: neovim
      when: install_neovim|default(true)

    - name: Include helix role
      include_role:
        name: helix
      when: install_helix|default(true)

    - name: Include python role
      include_role:
        name: python
      when: install_python|default(true)
