---
- name: Workstation Setup
  hosts: localhost
  connection: local
  force_handlers: true
  become: false

  pre_tasks:
    - name: Check if Password is correct
      become: true
      block:
        - name: Check Password
          command: echo "PW is correct"
          changed_when: false
          register: password_check
          timeout: 2
      rescue:
        - name: Password Alert
          ansible.builtin.fail:
            msg: Password timeout. Correct password?

  tasks:

    - name: Init config files
      file:
        state: touch
        path: "{{ ansible_env.HOME }}/{{item}}"
        mode: "u=rw,g=rw,o=r"
      with_items:
        - ".bashrc"
        - ".zshrc"

    - name: Check if .local/bin is in PATH
      command: "grep '.local/bin' {{ ansible_env.HOME }}/.bashrc"
      register: checkbashrc
      check_mode: false
      ignore_errors: true
      changed_when: false

    - name: Add to path if not present
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "export PATH=$PATH:{{ ansible_env.HOME }}/.local/bin"
      when: checkbashrc.rc == 1

    - name: .local/bin/ to Path in .zshrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: "export PATH=$PATH:{{ ansible_env.HOME }}/.local/bin"
        insertbefore: "BOF"

    - name: "Install system packages"
      become: true
      apt:
        name:
          - apt-transport-https
          - aptitude
          - fd-find
          - git
          - locate
          - magic-wormhole
          - neofetch
          - npm
          - rename
          - ripgrep # required for grep functionality in nvim telescope
          - shutter
          - sqlite3
          - tmux
          - tmux
          - tree
          - unzip
          - zsh
        state: latest
        update_cache: true
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Prepare VSCode dependencies
      become: true
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest

    - name: Add microsoft apt key
      become: true
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
    - name: Add VS Code apt repostitory
      become: true
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        state: present
        filename: vscode
    - name: Install VS Code
      become: true
      apt:
        name: code
        state: present

    - name: Ensure aliases are in ~/.gitconfig
      community.general.ini_file:
        path: "{{ ansible_env.HOME }}/.gitconfig"
        section: alias
        option: "{{ item.key }}"
        value: "{{ item.value }}"
        mode: "u=rw,g=rw,o=r"
        state: present
      loop:
        - { key: "st", value: "status" }
        - { key: "ss", value: "status -s" }
        - { key: "cm", value: "commit" }
        - { key: "co", value: "checkout" }
        - { key: "br", value: "branch" }
        - { key: "last", value: "log -1 HEAD" }
        - { key: "lol", value: "log --oneline" }
        - { key: "hh", value: "diff HEAD^ HEAD" }
        - { key: "ds", value: "diff --staged" }

    - name: Include zsh role
      include_role:
        name: zsh
      when: install_zsh | default(true)

    - name: "Symlink fdfind to fd"
      become: true
      file:
        src: /usr/bin/fdfind
        path: /usr/bin/fd
        state: link

    # For installing logseq and other AppImage applications
    # TODO: does not work on Debian -> and nvim/helix depend on this step
    - name: Install AppImageLauncher via PPA
      become: true
      apt_repository:
        repo: "ppa:appimagelauncher-team/stable"
        state: present
      notify: Update apt cache

    - name: Update apt cache
      become: true
      apt:
        update_cache: true

    - name: Install AppImageLauncher
      become: true
      apt:
        name: appimagelauncher
        state: present

    - name: Include tmux role
      include_role:
        name: tmux
      when: install_tmux | default(true) | bool

    - name: Include fzf role
      include_role:
        name: fzf
      when: install_fzf | default(true) | bool

    - name: Include zoxide role
      include_role:
        name: zoxide
      when: install_zoxide | default(true) | bool

    - name: Include neovim role
      include_role:
        name: neovim
      when: install_neovim | default(true) | bool

    - name: Include helix role
      include_role:
        name: helix
      when: install_helix | default(true) | bool

    - name: Include python role
      include_role:
        name: python
      when: install_python | default(true) | bool

    - name: Include cli_tools role
      include_role:
        name: cli_tools
      when: install_cli_tools | default(true) | bool

    - name: Include gui_apps role
      include_role:
        name: gui_apps
      when: install_gui_apps | default(false) | bool

    - name: Include lnav role
      include_role:
        name: lnav
      when: install_lnav | default(true) | bool

    - name: Include difftastic role
      include_role:
        name: difftastic
      when: install_difftastic | default(true) | bool
