- name: Download Helix
  get_url:
    url: https://github.com/helix-editor/helix/releases/download/23.05/helix-23.05-x86_64.AppImage
    dest: "{{ file_path }}"
  become: true

- name: Make helix executable
  file:
    path: "{{ file_path }}"
    mode: '0755'
  become: true

- name: Add to path as hx
  file:
    src: "{{ file_path }}"
    dest: /usr/local/bin/hx
    state: link
  become: true

- name: Add to path as helix
  file:
    src: "{{ file_path }}"
    dest: /usr/local/bin/helix
    state: link
  become: true

- name: Make default editor in bash
  lineinfile:
    path: "/home/{{ ansible_user_id }}/.bashrc"
    line: "export EDITOR=helix"


- name: Make default editor in zsh
  lineinfile:
    path: "/home/{{ ansible_user_id }}/.zshrc"
    line: "export EDITOR=helix"

- name: Install yaml-language-server globally
  # TODO: root
  become: true
  npm:
    name: yaml-language-server
    global: true
    version: next

- name: Install pyright
  become: true
  npm:
    name: pyright
    global: true

- name: Create config directory if it does not exist
  file:
    path: /home/{{ ansible_user_id }}/.config/helix/
    state: directory

- name: Copy languages.toml
  copy:
    src: config/helix/languages.toml
    dest: /home/{{ ansible_user_id }}/.config/helix/
    backup: yes
