- name: Download Helix
  get_url:
    url: https://github.com/helix-editor/helix/releases/download/23.05/helix-23.05-x86_64.AppImage
    dest: "{{ file_path }}"
    mode: "u=rwx,g=rx,o=rx"
  become: true

- name: Add to path as hx
  file:
    src: "{{ file_path }}"
    dest: /usr/local/bin/hx
    state: link
  become: true

- name: Add to path as helix
  file:
    src: "{{ file_path }}"
    dest: /usr/local/bin/helix
    state: link
  become: true

- name: Make default editor in bash
  lineinfile:
    path: "/home/{{ ansible_user_id }}/.bashrc"
    line: "export EDITOR=helix"

- name: Make default editor in zsh
  lineinfile:
    path: "/home/{{ ansible_user_id }}/.zshrc"
    line: "export EDITOR=helix"

- name: Install yaml-language-server globally
  # TODO: root
  become: true
  community.general.npm:
    name: yaml-language-server
    global: true
    version: next

- name: Install pyright
  become: true
  community.general.npm:
    name: pyright
    global: true

- name: Create config directory if it does not exist
  file:
    path: /home/{{ ansible_user_id }}/.config/helix/
    state: directory
    mode: "u=rwx,g=rwx,o=rx"

- name: Copy languages.toml
  copy:
    src: config/helix/languages.toml
    dest: /home/{{ ansible_user_id }}/.config/helix/
    mode: "u=rw,g=rw,o=r"
    backup: true

- name: Copy config.toml
  copy:
    src: config/helix/config.toml
    dest: /home/{{ ansible_user_id }}/.config/helix/
    mode: "u=rw,g=rw,o=r"
    backup: true
