- name: Install pip and venv
  apt:
    name:
      - python3-pip
      - python3-venv
    state: latest
  become: true

- name: Check if pipx is installed
  command: which pipx
  register: pipx_installed
  ignore_errors: true
  changed_when: false
  failed_when: false

- name: Install pipx
  when: pipx_installed.rc != 0
  block:
    - name: Pip install pipx
      pip:
        name: pipx
        state: present
        extra_args: --user
    - name: Pipx ensure path
      command: python3 -m pipx ensurepath
      changed_when: false
