- name: Check zoxide
  stat:
    path: "{{ ansible_env.HOME }}/.local/bin/zoxide"
  register: zoxide_installed

- name: Install zoxide
  when: not zoxide_installed.stat.exists
  block:
    - name: Download zoxide
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh
        dest: /tmp/zoxide-install.sh
        mode: "u=rwx,g=rx,o=rx"
    - name: Run installtion script
      command: bash /tmp/zoxide-install.sh
      changed_when: not zoxide_installed.stat.exists

- name: Register zoxide
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    backup: true
    line: eval "$(zoxide init bash)"
- name: Register zoxide in zsh
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    backup: true
    line: eval "$(zoxide init zsh)"
