- name: Make default shell
  user:
    user: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: true

- name: Install Oh-My-Zsh
  get_url:
    url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
    dest: /tmp/install.sh
    mode: u=rwx,g=rx,o=rx
  become: true
  tags: oh-my-zsh

- name: Check if .oh-my-zsh directory exists
  stat:
    path: /home/yannik/.oh-my-zsh
  register: oh_my_zsh_dir

- name: Install Oh-My-Zsh
  command: /tmp/install.sh --unattended
  tags: oh-my-zsh
  when: not oh_my_zsh_dir.stat.exists
  changed_when: not oh_my_zsh_dir.stat.exists

- name: Clone Pure repo
  git:
    repo: https://github.com/sindresorhus/pure.git
    dest: "{{ ansible_env.HOME }}/.zsh/pure"

- name: Add Pure to fpath
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'fpath+=({{ ansible_env.HOME }}/.zsh/pure)'

- name: Initialize prompt
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    block: |
      autoload -U promptinit; promptinit
      prompt pure
