- name: "Check fzf"
  stat:
    path: "{{ ansible_env.HOME }}/fzf/bin/fzf"
  register: fzf_installed

- name: "Clone fzf"
  git:
    repo: "https://github.com/junegunn/fzf.git"
    clone: true
    depth: 1
    dest: "{{ ansible_env.HOME }}/fzf"
    version: 0.42.0
  when: not fzf_installed.stat.exists

- name: "Install fzf"
  # Note, if not installed in zsh for some reason repeat $HOME/fzf/install --all manually
  command: "{{ ansible_env.HOME }}/fzf/install --all"
  when: not fzf_installed.stat.exists
  changed_when: not fzf_installed.stat.exists

- name: Set fzf options in shell bashrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: export FZF_DEFAULT_OPTS='--multi --no-height --extended'
- name: Set fzf options in zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: export FZF_DEFAULT_OPTS='--multi --no-height --extended'
