- name: "Configure vi-keybindings for tmux"
  lineinfile:
    dest: "/home/{{ ansible_user_id }}/.tmux.conf"
    line: "set-window-option -g mode-keys vi"
    create: true
    mode: "u=rw,g=rw,o=r"

# https://github.com/helix-editor/helix/wiki/Troubleshooting#when-using-tmux-or-screen-there-is-a-delay-after-hitting-escape-before-its-registered
- name: "Fix helix slow return to normal mode"
  lineinfile:
    dest: "/home/{{ ansible_user_id }}/.tmux.conf"
    line: "set -sg escape-time 0"
