- name: Check if executable exists in /opt/
  stat:
    path: /opt/difft
  register: difft_installed

- name: Install
  when: not difft_installed.stat.exists
  block:
    - name: Download
      get_url:
        # march 2024
        url: https://github.com/Wilfred/difftastic/releases/download/0.56.1/difft-x86_64-unknown-linux-gnu.tar.gz
        dest: "/tmp/"
        mode: "u=rwx,g=rx,o=rx"
    - name: Extract archive
      ansible.builtin.unarchive:
        src: "/tmp/difft-x86_64-unknown-linux-gnu.tar.gz"
        dest: "/tmp/"
    - name: Move to opt
      become: true
      copy:
        src: /tmp/difft
        dest: /opt/
        mode: "u=rwx,g=rx,o=rx"
    - name: Remove original
      file:
        path: /tmp/difft
        state: absent
    - name: Create symlink
      become: true
      file:
        src: /opt/difft
        dest: /usr/local/bin/difft
        state: link
        force: true
