- name: Remove neovim if installed
  apt:
    name: neovim
    state: absent
  become: true

- name: Download neovim appimage
  get_url:
    url: https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
    dest: /opt/nvim.appimage
    mode: '0755'
  become: true

- name: Create symlink for nvim
  file:
    src: /opt/nvim.appimage
    dest: /usr/local/bin/nvim
    state: link
    force: true
  become: true
