- name: Remove neovim if installed
  apt:
    name: neovim
    state: absent
  become: true

- name: Download neovim appimage
  get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.9.5/nvim.appimage
    dest: /opt/nvim.appimage
    mode: "u=rwx,g=rx,o=rx"
  become: true

- name: Create symlink for nvim
  file:
    src: /opt/nvim.appimage
    dest: /usr/local/bin/nvim
    state: link
    force: true
  become: true

- name: Check nvim config
  stat:
    path: "{{ ansible_env.HOME }}/.config/nvim"
  register: nvim_cfg_dir

- name: Clone kickstart.nvim repository
  git:
    repo: https://github.com/nvim-lua/kickstart.nvim.git
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    # 24 Dec 2023
    version: 4d0dc8d4b1bd6b94e59f7773158149bb1b0ee5be
    force: true
  when: not nvim_cfg_dir.stat.exists
  notify: PostInstallationHandler
